#
# WORDPRESS OWASP CRS TUNING
#

# ================================
# WordPress REST API
# ================================

SecRule REQUEST_URI "@rx ^/wp-json/" \
"id:10001,\
phase:1,\
pass,\
nolog,\
ctl:ruleRemoveById=920450"

# ================================
# Gutenberg Editor Fix
# ================================

SecRule REQUEST_URI "@rx ^/wp-json/wp/v2/" \
"id:10002,\
phase:1,\
pass,\
nolog,\
ctl:ruleRemoveById=941100,\
ctl:ruleRemoveById=941160,\
ctl:ruleRemoveById=949110"

# ================================
# WordPress Media Upload
# ================================

SecRule REQUEST_URI "@rx ^/wp-admin/async-upload.php" \
"id:10003,\
phase:1,\
pass,\
nolog,\
ctl:ruleRemoveById=920420"

# ================================
# WordPress Admin AJAX
# ================================

SecRule REQUEST_URI "@rx ^/wp-admin/admin-ajax.php" \
"id:10004,\
phase:1,\
pass,\
nolog,\
ctl:ruleRemoveById=941100,\
ctl:ruleRemoveById=941160"

# ================================
# WordPress Login
# ================================

SecRule REQUEST_URI "@rx ^/wp-login.php" \
"id:10005,\
phase:1,\
pass,\
nolog,\
ctl:ruleRemoveById=942100"

# ================================
# WordPress XMLRPC
# ================================

SecRule REQUEST_URI "@rx ^/xmlrpc.php" \
"id:10006,\
phase:1,\
pass,\
nolog,\
ctl:ruleRemoveById=942430"

# ================================
# WordPress Comments
# ================================

SecRule REQUEST_URI "@rx ^/wp-comments-post.php" \
"id:10007,\
phase:1,\
pass,\
nolog,\
ctl:ruleRemoveById=941100"

# ================================
# WordPress Theme Editor
# ================================

SecRule REQUEST_URI "@rx ^/wp-admin/theme-editor.php" \
"id:10008,\
phase:1,\
pass,\
nolog,\
ctl:ruleRemoveById=933150"

# ================================
# WordPress Plugin Editor
# ================================

SecRule REQUEST_URI "@rx ^/wp-admin/plugin-editor.php" \
"id:10009,\
phase:1,\
pass,\
nolog,\
ctl:ruleRemoveById=933150"

SecRule REQUEST_URI "@rx ^/wp-json/" \
"id:10051,\
phase:1,\
pass,\
nolog,\
ctl:ruleRemoveById=920450"
